# -*- coding: utf-8 -*-
"""Scheme exports used by VideoAtlas."""

from .canonical_registry import (
    ALLOWED_EVIDENCE,
    ALLOWED_GENRES,
    DEFAULT_PROFILE,
    PROFILES,
    ALLOWED_SAMPLING_PROFILES,
    ALLOWED_SEGMENTATION_PROFILES,
    ALLOWED_SIGNAL_PRIORITIES,
    CAPTION_PROFILES,
    DEFAULT_CAPTION_PROFILE,
    DEFAULT_SEGMENTATION_PROFILE,
    SAMPLING_PROFILE_CONFIGS,
    SEGMENTATION_PROFILES,
    resolve_caption_profile,
    resolve_profile,
    resolve_sampling_profile,
    resolve_segmentation_profile,
)
from .canonical_atlas import (
    AtlasSegment,
    AtlasUnit,
    CandidateBoundary,
    CaptionedSegment,
    CanonicalAtlas,
    CanonicalExecutionPlan,
    CanonicalCompositionResult,
    Profile,
    CaptionProfile,
    CaptionSpecification,
    FrameSamplingProfile,
    FinalizedSegment,
    SamplingConfig,
    SegmentationProfile,
    SegmentationSpecification,
)
from .canonical_request import CanonicalCreateRequest
from .acquisition import SourceInfoRecord, SourceAcquisitionResult, SourceMetadata
from .derived_atlas import DerivationPolicy, DerivationResultInfo, DerivedAtlas, DerivedSegmentDraft

__all__ = [
    "ALLOWED_EVIDENCE",
    "ALLOWED_GENRES",
    "DEFAULT_PROFILE",
    "PROFILES",
    "ALLOWED_SAMPLING_PROFILES",
    "ALLOWED_SEGMENTATION_PROFILES",
    "ALLOWED_SIGNAL_PRIORITIES",
    "AtlasSegment",
    "AtlasUnit",
    "CAPTION_PROFILES",
    "CandidateBoundary",
    "CaptionedSegment",
    "CanonicalExecutionPlan",
    "CanonicalCreateRequest",
    "CanonicalAtlas",
    "CanonicalCompositionResult",
    "CaptionProfile",
    "CaptionSpecification",
    "Profile",
    "DEFAULT_CAPTION_PROFILE",
    "DEFAULT_SEGMENTATION_PROFILE",
    "DerivedAtlas",
    "DerivedSegmentDraft",
    "DerivationPolicy",
    "DerivationResultInfo",
    "FrameSamplingProfile",
    "FinalizedSegment",
    "SAMPLING_PROFILE_CONFIGS",
    "SEGMENTATION_PROFILES",
    "SamplingConfig",
    "SegmentationProfile",
    "SegmentationSpecification",
    "SourceInfoRecord",
    "SourceMetadata",
    "SourceAcquisitionResult",
    "resolve_caption_profile",
    "resolve_profile",
    "resolve_sampling_profile",
    "resolve_segmentation_profile",
]
